### PR TITLE
Create Chachinus doveflies Finland.yml

### PR DESCRIPTION
**Pull request by HannaLaakkonen**
Not sure what to put here

### CODE REVIEW

**Review by wkmor1 — CHANGES_REQUESTED** [review]
Hei Hanna,

So this would work but I want to also test out asking the user to make changes
before they submit.

Could you do the following to your collections text:
- Remove ".yml" from the end of your "name:" field value as you don't need that here.
- Make your ORCID a full URL (add https://orcid.org/ to the start)

You can make these changes here https://github.com/HannaLaakkonen/vrc/blob/patch-2/collections/Chachinus%20doveflies%20Finland.yml 
Just click the little pencil on the upper right hand side of the page.
After you make the changes you click the green "Commit changes..." button.
In the pop up that opens you can (but you don't have to) adjust the commit message and add an extended description of the changes.
Then click "Commit changes".
Done.

Cheers,

Will

**Review by wkmor1 — APPROVED** [review]
Thanks! That looks good now

**Comment by wkmor1** [comment]
Actually wasn't quite correct. I had to remove your name as that was not supposed to be there. I can see why you thought it should go there though. I will update the instructions to make it more clear how to use the template. Where not to write text as well as where "to" write text.

**Comment by wkmor1** [comment]
Your collection is now in the library https://luomus.github.io/vrc/

**Comment by wkmor1** [comment]
see here https://luomus.github.io/vrc/vrc-5494983011480059d2dbb8b30b78c443.json

**Comment by wkmor1** [comment]
Any comments on the process?

**Comment by HannaLaakkonen** [comment]
Hi Will,

Thanks a lot for planning and working with this. It looks good, although I'm not sure if I understand the process.. we'll need to get back to this after the holidays, as I have some questions. To start with, would the setting-up of the collections be this kind of process and if so, who will do that work which you did this time?

cheers
hanna




________________________________
Lähettäjä: wkmor1 ***@***.***>
Lähetetty: perjantai 19. heinäkuuta 2024 15.51
Vastaanottaja: luomus/vrc ***@***.***>
Kopio: Laakkonen, Hanna M ***@***.***>; Author ***@***.***>
Aihe: Re: [luomus/vrc] Create Chachinus doveflies Finland.yml (PR #2)


Any comments on the process?

**Comment by wkmor1** [comment]
Yes. Let's discuss after the break

**Pull request merged**
